import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Nav } from '@/components/Nav'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isDark, setIsDark] = useState(false)
  const onSubmitHandler = (e) => {
    e.preventDefault()
  }
  const onIsDark = (dark) => {
    setIsDark(dark)
    console.log(isDark)
  }
  return (
    <>
      <Head>
        <title>Unlocking Your Writing Genius</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav onIsDark={onIsDark} />
      <main className={!isDark ? styles.main : ` ${styles.main} bg-[#0d1a2e]`}>
        <div className={styles.container}>
          <div className={styles.searchWrapper}>
            <form onSubmit={onSubmitHandler}>
              <span className={styles.form}>
                <span className={styles.searchIcons}>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-6 h-6"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
                    />
                  </svg>
                </span>
                <span className={styles.searchInput}>
                  <input type="text" placeholder="Searching anything" />
                </span>
                <span className={styles.searchButton}>
                  <button>Search</button>
                </span>
              </span>
            </form>
          </div>
          <div
            className={
              !isDark
                ? styles.option_container
                : `${styles.option_container} ${styles.dark__select}`
            }
          >
            <ul className={styles.options}>
              <li className={styles.optionsWrapper}>
                <label>SEO Enabled</label>
                <input type="checkbox" />
              </li>
              <li className={styles.optionsWrapper}>
                {' '}
                <label>Technical</label>
                <input type="checkbox" />
              </li>
              <li className={styles.optionsWrapper}>
                {' '}
                <label>Non Technical</label>
                <input type="checkbox" />
              </li>
              <li className={styles.optionsWrapper}>
                {' '}
                <label>10 Result</label>
                <input type="checkbox" />
              </li>
            </ul>
            <span className={styles.optionsWrapper}>
              <label>Field</label>
              <select className={styles.selectWrapper}>
                {[
                  { value: 'Frontend' },
                  { value: 'Backend' },
                  { value: 'Cloud' },
                  { value: 'UI/UX' },
                  { value: 'Web3' },
                ].map((item) => (
                  <option value={item} key={item}>
                    {item.value}
                  </option>
                ))}
                <option value="" key="" className={styles.selectWrapper}>
                  Frontend
                </option>
              </select>
            </span>
          </div>

          <div style={{ marginTop: '2rem' }}>
            <div class="flex flex-col">
              <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
                <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
                  <div class="overflow-hidden">
                    <table class="w-4/5 mt-5" style={{ margin: '0 auto' }}>
                      {' '}
                      <thead class="bg-white border-b">
                        <tr>
                          <th
                            scope="col"
                            class="text-sm font-medium text-gray-900 px-6 py-4 text-left"
                          >
                            Generated Topics
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {[{}].map((item) => (
                          <>
                            <tr class="bg-gray-100 border-b">
                              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap font-medium">
                                <a href="#" style={{ color: 'blue' }}>
                                  Easily Create An NFT App Using The New Infura
                                  NFT SDK TypeScript
                                </a>
                              </td>
                            </tr>
                            <tr class="bg-gray-100 border-b">
                              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap font-medium">
                                <a href="#" style={{ color: 'blue' }}>
                                  Easily Create An NFT App Using The New Infura
                                  NFT SDK TypeScript
                                </a>
                              </td>
                            </tr>
                          </>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
